

export const API_REQUEST="API_REQUEST"
export const AUTHENTICATION_START="AUTHENTICATION_START"
export const AUTHENTICATION_SUCCESS="AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAIL="AUTHENTICATION_FAIL"


export const LOGOUT="LOGOUT"