

export const API_REQUEST="API_REQUEST"
export const AUTHENTICATION_START="AUTHENTICATION_START"
export const AUTHENTICATION_SUCCESS="AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAIL="AUTHENTICATION_FAIL"


export const LOGOUT="LOGOUT"


export const INVITATION_API_REQUEST="INVITATION_API_REQUEST"
export const SEND_INVITATION_START="SEND_INVITATION_START"
export const SEND_INVITATION_SUCCESS="SEND_INVITATION_SUCCESS"
export const SEND_INVITATION_FAIL="SEND_INVITATION_FAIL"



export const SIGNUP_START="SIGNUP_START"
export const SIGNUP_FAIL="SIGNUP_FAIL"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"